In [1]:
import numpy as np

A= np.array([[1,2,3,4],
           [1,2,3,4],
           [1,2,3,4]])
print(A)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [2]:
cal = A.sum(axis=0)
# sum vertically

In [3]:
print(cal)

[ 3  6  9 12]


In [5]:
percentage = 100*A/cal.reshape(1,4)
# reshape is very cheap to call
# divide by 1 by 4 matrix
print(percentage)

#(3,4 )/(1,4)
#eg [1,2,3,4] + 100 equal to [101, 102, 103, 104]
# (2,n) + (1, n)
#[[1,2,3],[4,5,6]] + [100, 200, 300]
#(m,n) + (m,1)
#[[1,2,3],[4,5,6]] + [[100],[200]]
#[[1,2,3],[4,5,6]] + [[100,100,100],[200,200,200]]=[[101,102,103],[204,205,206]]


[[ 33.33333333  33.33333333  33.33333333  33.33333333]
 [ 33.33333333  33.33333333  33.33333333  33.33333333]
 [ 33.33333333  33.33333333  33.33333333  33.33333333]]


In [6]:
#general principle for broadcasting in python
# (m,n)  +/-/*/divide (1,n) ->(m,n) copy by m times
# (m,n)  +/-/*/divide (m,1) ->(m,n) copy by n times
# (m,n)  +/-/*/divide R ->(m,n) copy by m, and n times

In [ ]:
#in matlab, bsxfun function has similar usage as broadcasting