In [4]:
import numpy as np

#construct vectors
a = np.random.randn(5)


In [6]:
print(a)

[-1.78763306 -0.75271596  1.39995718 -0.23141592  0.92684198]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[-1.78763306 -0.75271596  1.39995718 -0.23141592  0.92684198]


In [9]:
print(np.dot(a,a.T))

6.63468275169


In [10]:
# the above result is suppose to be n*n matrix
a=np.random.randn(5,1)

In [11]:
print(a)

[[ 0.1847788 ]
 [ 0.35366996]
 [-0.02537454]
 [ 1.18159078]
 [ 0.62276586]]


In [12]:
print(a.T)

[[ 0.1847788   0.35366996 -0.02537454  1.18159078  0.62276586]]


In [13]:
print(np.dot(a,a.T))

[[  3.41432057e-02   6.53507113e-02  -4.68867633e-03   2.18332929e-01
    1.15073929e-01]
 [  6.53507113e-02   1.25082440e-01  -8.97421103e-03   4.17893163e-01
    2.20253575e-01]
 [ -4.68867633e-03  -8.97421103e-03   6.43867068e-04  -2.99823176e-02
   -1.58023946e-02]
 [  2.18332929e-01   4.17893163e-01  -2.99823176e-02   1.39615678e+00
    7.35854397e-01]
 [  1.15073929e-01   2.20253575e-01  -1.58023946e-02   7.35854397e-01
    3.87837314e-01]]


In [14]:
print((np.dot(a,a.T)).shape)

(5, 5)
